#!/bin/bash
set -e
xdebug.remote_port=9004 \n\
xdebug.remote_host=10.10.2.107 \n\

echo -e "xdebug.remote_port=9004 \n\
xdebug.remote_host=10.10.2.107" >> /usr/local/etc/php/conf.d/xdebug.ini ;

exec php-fpm